products:
  - name: PS5 Drive Edition
    value: https://www.vatanbilgisayar.com/sony-playstation-5-oyun-konsolu.html
  - name: PS5 Digital Edition
    value: https://www.vatanbilgisayar.com/sony-playstation-5-digital-surum-oyun-konsolu.html

